[tool.poetry]
name = "bonestraker"
version = "0.1.0"
description = ""
authors = ["TwelveFaced <twofaced-janus@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
opencv-python = "^4.11.0.86"
mediapipe = "^0.10.21"
pygame = "^2.6.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
